### ISSUE TITLE
TypeError at /PassPercentage/lines_charts/x86_64/networkstorage_nbd/

### ISSUE THREAD

**Issue by zixi-chen** [YongxueHong/PassPercentage#18]
writelines() argument must be a sequence of strings

Request Method: | GET
-- | --
http://dell-per715-04-vm-passpercentage.lab.eng.pek2.redhat.com:8000/PassPercentage/lines_charts/x86_64/networkstorage_nbd/
1.9.10
TypeError
writelines() argument must be a sequence of strings
/home/yhong/PassPercentage/PassPercentage/utils.py in create_datapoints_line, line 155
/usr/bin/python
2.7.5
['/home/yhong/PassPercentage',  '/usr/lib64/python27.zip',  '/usr/lib64/python2.7',  '/usr/lib64/python2.7/plat-linux2',  '/usr/lib64/python2.7/lib-tk',  '/usr/lib64/python2.7/lib-old',  '/usr/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7/site-packages',  '/usr/lib64/python2.7/site-packages/gtk-2.0',  '/usr/lib/python2.7/site-packages']
Wed, 10 Mar 2021 11:45:41 +0800

Environment:

Request Method: GET
Request URL: http://dell-per715-04-vm-passpercentage.lab.eng.pek2.redhat.com:8000/PassPercentage/lines_charts/x86_64/networkstorage_nbd/

Django Version: 1.9.10
Python Version: 2.7.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'PassPercentage']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/yhong/PassPercentage/PassPercentage/views.py" in display_lines_charts_from_column
  87.                                       context_dict['xml_name'], False)

File "/home/yhong/PassPercentage/PassPercentage/utils.py" in create_datapoints_line
  155.     file.writelines(context)

Exception Type: TypeError at /PassPercentage/lines_charts/x86_64/networkstorage_nbd/
Exception Value: writelines() argument must be a sequence of strings

**Comment by YongxueHong** [comment]
Hi @zixi-chen 
Fixed it by https://github.com/YongxueHong/PassPercentage/pull/21
Then you could check it by http://dell-per715-04-vm-passpercentage.lab.eng.pek2.redhat.com:8000/PassPercentage/lines_charts/x86_64/network-storage/
Thanks.
