### ISSUE TITLE
Please help to collect the correct auto result for feature memory on ppc64le

### ISSUE THREAD

**Issue by MiriamDeng** [YongxueHong/PassPercentage#29]
On ppc64le, in memory page,
http://dell-per715-04-vm-passpercentage.lab.eng.pek2.redhat.com:8000/PassPercentage/lines_charts/ppc64le/memory/
There are three main issues as followings, 
1.The pass percentage and chart can't be updated if there's new test is executed. 
2.Collection the some scratches build's data.
3.Some error of 100% was uploaded too.

**Comment by YongxueHong** [comment]
Fixed by https://github.com/YongxueHong/PassPercentage/pull/30
CC @MiriamDeng

**Comment by MiriamDeng** [comment]
Thanks yhong.
The latest result can be uploaded to the server now, thanks for your effort.
