### ISSUE TITLE
Remove some features data from passpercentage

### ISSUE THREAD

**Issue by leidwang** [YongxueHong/PassPercentage#52]
We have reached an agreement with the developers on the priority of features. And we don't need functional tests for these low-priority features.So there is no need to track these features's passpercentage.

Low priority feature name: **viorng, vioinput, pvpanic**. CC @vivianQizhu 

Hi @YongxueHong Could you please help to remove it?Thanks a lot!

**Comment by leidwang** [comment]
Hi @YongxueHong Could you please help to check it when you are free? Thanks.

**Comment by YongxueHong** [comment]
Hi @leidwang 
Sorry for forgetting it, will handle it later.
